### ISSUE TITLE
[Refonte] Fix & Update du site (et de la carte/explorateur BAN)

### ISSUE THREAD

**Issue by vinsag** [BaseAdresseNationale/adresse.data.gouv.fr#1917]
BUG* :
- [x] https://github.com/BaseAdresseNationale/adresse.data.gouv.fr/issues/1913 (Erreur sur l'affichage des numéros pour les lieux dits)
- [x] https://github.com/BaseAdresseNationale/adresse.data.gouv.fr/issues/1914 (Sur les résultats de recherches de la carte)
- [x] Bug affichage de la carte entre les bandeaux haut et bas au chargement (Sur la carte)
- [x] Problème lien sur la page commune pour aller vers la carte
- [x]  https://github.com/BaseAdresseNationale/adresse.data.gouv.fr/issues/1926
- [x] Dark-mode : debugguer les elements cassé
- [x] #1948 (Revoir toutes les pop-up des points sur la carte)
- [x] #1933

Ergonomie :
- [ ] https://github.com/BaseAdresseNationale/adresse.data.gouv.fr/issues/1922 - Mettre un tooltip (code INSEE)
- [x] https://github.com/BaseAdresseNationale/adresse.data.gouv.fr/issues/1923*
- [x] Corrections orthographiques*
- [ ] https://github.com/BaseAdresseNationale/adresse.data.gouv.fr/issues/1924
- [x] #1929
- [x] #1930

Ajustement Graphique :
- [X] Enlever l’italique du numéro
- [x] #1948* (Mettre en valeur le picto certification au niveau de l'adresse comme sur le site actuel*)
- [x] #1954* (Ajouter le picto certification au niveau de la commune comme sur le site actuel*)
- [x] #1948 (Un seul badge certifié)

Autre :
- [x] Sur la certification : mention à modifier*
- [x] #1931*

----------------------------------

En cours d'etude :
- [x] #1928
- [ ] Manquant : les sources de l’assemblage

**Comment by FrederiqWilliams** [comment]
Pour la mention à modifier sur la certification : proposition de se rapprocher de la définition de la spec BAL : 
 "indique que la commune a validé l'exactitude des informations de l'adresse"

**Comment by nkokla** [comment]
Premiere PR : 
https://github.com/BaseAdresseNationale/adresse.data.gouv.fr/pull/1927

**Comment by vinsag** [comment]
On peut fermer ce ticket de suivi, les 2 tickets restant seront pris dans une nouvelle liste de modifications
